# Generated by Django 5.2.4 on 2025-09-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcardtemplate',
            name='html',
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='id_templates/backgrounds/'),
        ),
        migrations.AddField(
            model_name='idcardtemplate',
            name='fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='idcardtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
