# Generated by Django 5.2.4 on 2025-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idms', '0002_remove_idcardtemplate_html_idcardtemplate_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcardtemplate',
            name='card_size_mm',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
