# Generated by Django 5.2.4 on 2025-09-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idms', '0003_idcardtemplate_card_size_mm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='father_name',
            new_name='fatherName',
        ),
    ]
